// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://batnflwsnbtyobzcpegj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdG5mbHdzbmJ0eW9iemNwZWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzY4NzEsImV4cCI6MjA4ODI1Mjg3MX0.01xEmZdXCMvxRaituUFSqR4BEx8kbajSyY4v1QBSHdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});